[project]
name = "aoc-2025"
version = "0.1.0"
description = "Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "advent-of-code-data>=2.1.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pudb>=2025.1.3",
    "ruff>=0.14.7",
]
